# -- Site Configuration --
# Refer to the theme docs for more details abouts each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
baseURL = "https://xdpcs.github.io"
languageCode = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0
title = "XdpCs's blog"
googleAnalytics = "G-MEASUREMENT_ID"

[params.utterances]
owner = "XdpCs"
repo = "xdpcs.github.io"

[outputs]
home = ["HTML", "RSS", "JSON"]
