languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "XdpCs's Website"
description = "XdpCs's blog"
copyright = "© Alan Xu"

dateFormat = "2 January 2006"

[author]
name = "XdpCs"
image = "images/avatar.jpeg"
headline = "Golang Developer"
bio = "Talking about technology with a glow in the eye."
links = [
    { email = "mailto:xdpcsyy@gmail.com" },
    { github = "https://github.com/XdpCs" },
]
